
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sdnwhiteblacks.apps.quark.io
spec:
  group: apps.quark.io
  names:
    kind: SDNWhiteBlack
    listKind: SDNWhiteBlackList
    plural: sdnwhiteblacks
    singular: sdnwhiteblack
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: The Schema for the SDNWhiteBlack API
          type: object
          properties:
            spec:
              description: SDNWhiteBlackSpec defines main field
              type: object
              properties:
                whiteList:
                  type: array
                  items:
                    type: string
                blackList:
                  type: array
                  items:
                    type: string
                    
